spring:
  application:
    name: auto-search-service
  profiles:
    active: ${APP_PROFILE}
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"

auto-search:
  expiration:
    min-days: 1
    max-days: 7
    scheduler:
      cron: "0 0 * * * *"
      page-size: 100